boats/accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from django.contrib.auth.views import login, logout
from django.contrib.auth.views import password_reset
from django.views.generic import TemplateView
from forms import LoginForm

urlpatterns = patterns('',
    url(r'^success/$', TemplateView.as_view(template_name='accounts/success.html')),
    url(r'^confirm_registration/(?P<link>.+)/$', 'boats.accounts.views.confirm_registration'),
    url(r'^about/', 'boats.accounts.views.about_signup'),
    url(r'^change/$', 'boats.accounts.views.get_form_change'),
    url(r'^change/password/$', 'boats.accounts.views.get_form_change_password'),
    url(r'^login/$', 'boats.accounts.views.authorize'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logged_out.html'}),
    url(r'^password_reset/', include('password_reset.urls')),
    url(r'^bookmarks/$', 'boats.accounts.views.show_bookmarks'),
    url(r'^my_ads/$', 'boats.accounts.views.show_my_ads'),
    url(r'^del_my_ad/(?P<object_id>\d+)/$', 'boats.accounts.views.del_my_ad'),
    url(r'^send_mail_to_author/(?P<id>\d+)/$', 'boats.accounts.views.send_mail_to_author', name="send_mail_to_author"),
    url(r'^add_bookmark/(?P<content_type>\w+)/(?P<object_id>\d+)/$', 'boats.accounts.views.add_bookmark', name="add_bookmark"),
)

boats/catalog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings



urlpatterns = patterns('boats.catalog.views',
    url(r'^$', 'catalog_list', name='catalog_list'),
    url(r'brand/details/(?P<slug>\w+)/$', 'brand_details', name='brand_details'),
    url(r'brand/list/(?P<slug>\w+)/$', 'brand_list', name='brand_list'),
    url(r'brand/all/$', 'brand_all', name='brand_all'),

    url(r'product/details/(?P<slug>\w+)/$', 'product_details', name='product_details'),
    url(r'boats/search/$', 'boats_search', name='boats_search'),


    url(r'ads/$', 'ads_list', name='ads_list'),
    url(r'ads/list/ajax/$', 'ads_block_list', name='ads_block_list'),
    url(r'ads/filters/ajax/$', 'ads_block_filters', name='ads_block_filters'),

    url(r'ads/detail/(?P<id>\d+)/$', 'ads_detail', name='ads_detail'),
    url(r'ads/add/$', 'ad_add', name='ad_add'),
    url(r'ads/edit/(?P<id>\d+)/$', 'ad_edit', name='ad_edit'),
    url(r'ads/add/filter/ajax/$', 'ads_add_filter', name='ads_add_filter'),
    url(r'ads/del/filter/(?P<type>\w+)/$', 'ads_del_filter', name='del'),

    url(r'ad/image/delete/(?P<pk>\d+)/$', 'adimage_delete', name='adimage_delete'),
    #url(r'^$', 'image_view', name='main'),
    #url(r'^multi/$', 'multiuploader', name='multi'),

    url(r'^search/model/ajax/$', 'search_model_ajax', name='search_model_ajax'),
    url(r'^ad/country/ajax/$', 'country_select_ajax', name='country_select_ajax'),
    url(r'^admin/product/type/ajax/$', 'admin_type_select', name='admin_type_select'),

    url(r'^howto_buy_or_sell/$', 'howto_buy', name='howto_buy_or_sell'),
)

boats/gallery/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include

urlpatterns = patterns('boats.gallery.views',
    url(r'^all/$', 'gallery_list', name = "gallery_all"),
    url(r'^get/(?P<slug>\w+)/$', 'one_gallery', name = "one_gallery"),
    url(r'^load_more/$', 'load_more', name = "load_more_galeries"),
)

boats/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from boats.feeds import LatestArticles
from django.views.generic.base import RedirectView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='/home/')),
    url(r'^home/$', 'boats.main.views.home'),
    url(r'^gallery/', include('boats.gallery.urls')),
    url(r'^articles/', include('boats.articles.urls')),
    url(r'^catalog/', include('boats.catalog.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^search/', include('haystack.urls')),
    url(r'^comments/', include('boats.threadedcomments.urls')),
    url(r'^accounts/', include('boats.accounts.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'', include('social_auth.urls')),
    url(r'^feeds/articles/$',LatestArticles()),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
   )

boats/catalog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea ,TextInput, PasswordInput , ModelChoiceField , ChoiceField
from boats.catalog.models import Ad, Product, WaterTransport, TypeTransport, Brand, FuelType, Country, State, Year, BodyMaterial, BodyShape, EngineNumber, EngineType, EnginePower, Currency, AdPhone
from captcha.fields import CaptchaField
from django.forms.models import inlineformset_factory
from boats.accounts.models import User

KIND_CHOICES = (WaterTransport.objects.all().values_list('id', 'name'))
TYPE_CHOICES = (TypeTransport.objects.all().values_list('id', 'name'))
BRAND_CHOICES = (Brand.objects.all().values_list('id', 'name'))
FUEL_TYPE_CHOICES = (FuelType.objects.all().values_list('id', 'name'))
COUNTRY_CHOICES = (Country.objects.all().values_list('id', 'name'))
STATE_CHOICES = (State.objects.all().values_list('id', 'name'))
YEAR_CHOICES = (Year.objects.all().values_list('id', 'year'))
CURRENCY_CHOICES = (Currency.objects.all().values_list('id', 'name'))
BODY_MATERIAL_CHOISES = (BodyMaterial.objects.all().values_list('id', 'name'))
BODY_SHAPE_CHOISES = (BodyShape.objects.all().values_list('id', 'name'))
ENGINE_NUMBER_CHOISES = (EngineNumber.objects.all().values_list('id', 'number'))
ENGINE_TYPE_CHOISES = (EngineType.objects.all().values_list('id', 'name'))
ENGINE_POWER_CHOISES = (EnginePower.objects.all().values_list('id', 'power'))
PRODUCT_CHOICES = (Product.objects.all().values_list('id', 'title'))
AD_CHOICES = (Ad.objects.all().values_list('id', 'model'))
YACHT_STATE_CHOICES = (
        ('1', 'Новое'),
        ('2', 'Б/У'),
    )

IN_STOCK_CHOICES = (
        ('1', 'В наличии'),
        ('2', 'В пути'),
        ('3', 'Под заказ'),
    )

from itertools import chain
from django.forms import RadioSelect
from django.utils.encoding import force_unicode

class RadioSelectNotNull(RadioSelect):
    def get_renderer(self, name, value, attrs=None, choices=()):
        """Returns an instance of the renderer."""
        if value is None: value = ''
        str_value = force_unicode(value) # Normalize to string.
        final_attrs = self.build_attrs(attrs)
        choices = list(chain(self.choices, choices))
        if choices[0][0] == '':
            choices.pop(0)
        return self.renderer(name, str_value, final_attrs, choices)



class AdAddForm(forms.ModelForm):
    def __init__(self, author, *args, **kwargs):
        self.author = author
        super(AdAddForm, self).__init__(*args, **kwargs)
        self.fields['kind'].empty_label = None
        self.fields['in_stock'].empty_label = None

    length_ft = forms.FloatField(label="Длинна(футы)")
    width_ft  = forms.FloatField(label="Ширина(футы)")
    captcha   = CaptchaField(label="Каптча")
    contract_cost = forms.BooleanField(label="Цена",required=False)

    def save(self):
        form = super(AdAddForm, self).save(commit= False)
        cd = self.cleaned_data
        form.author = self.author
        form.active = True
        if cd['contract_cost']:
            form.cost=0
        form.save()
        return form

    def clean(self):
        cleaned_data = super(AdAddForm, self).clean()
        cost = cleaned_data.get('cost')
        currency = cleaned_data.get('currency')
        contract_cost = cleaned_data.get('contract_cost')

        if not(cost and currency) and contract_cost==False:
            raise forms.ValidationError("Введите цену или выберите договорную.")

        return cleaned_data

    class Meta:
        model = Ad
        widgets = {
            'kind': forms.RadioSelect(),
            'in_stock': RadioSelectNotNull(),
            'yacht_state': RadioSelectNotNull(),
        }
        exclude = ('author','views')

class AdAddPhoneForm(forms.ModelForm):
    class Meta:
        model = AdPhone

AdAddPhoneFormSet = inlineformset_factory(Ad, AdPhone, extra=1, max_num=10, can_delete=False)

class CatalogBoatSearchForm(forms.Form):
    boat_brand = forms.ChoiceField(widget=forms.Select(attrs={}), choices=BRAND_CHOICES)
    boat_length_from = forms.FloatField(label="from", required=False, widget = forms.TextInput(attrs={} ))
    boat_length_to = forms.FloatField(label="to", required=False, widget = forms.TextInput(attrs={} ))
    boat_kind = forms.ChoiceField(widget=forms.RadioSelect(attrs={}), required=False, choices=([('',u'Все')]+list(WaterTransport.objects.all().values_list('id', 'name'))))
    boat_year_from = forms.IntegerField(label="from", required=False, widget = forms.TextInput())
    boat_year_to = forms.IntegerField(label="to", required=False, widget = forms.TextInput())
    boat_cost_from = forms.FloatField(label="from", required=False, widget = forms.TextInput())
    boat_cost_to = forms.FloatField(label="to", required=False, widget = forms.TextInput())

class CatalogModelSearchForm(forms.Form):
    model_brand = forms.ChoiceField(widget=forms.Select(attrs={}), choices=BRAND_CHOICES)
    model_product = forms.ChoiceField(widget=forms.Select(attrs={}), choices=PRODUCT_CHOICES)


class CatalogAdSearchForm(forms.Form):
    country = forms.ChoiceField(widget=forms.Select(attrs={"class":"select200px"}), choices=COUNTRY_CHOICES)
    state = forms.ChoiceField(widget=forms.Select(attrs={"class":"select200px"}), choices=STATE_CHOICES)
    brand = forms.ChoiceField(widget=forms.Select(attrs={"class":"select200px"}), choices=([('',u'Все')]+list(Brand.objects.all().values_list('id', 'name'))))
    ad = forms.ChoiceField(widget=forms.Select(attrs={}), choices=AD_CHOICES)
    length_from = forms.FloatField(label="from", required=False, widget = forms.TextInput(attrs={ }))
    length_to = forms.FloatField(label="to", required=False, widget = forms.TextInput(attrs={"class":"pull-right"} ))
    year_from = forms.IntegerField(label="from", required=False, widget = forms.TextInput(attrs={ }))
    year_to = forms.IntegerField(label="to", required=False, widget = forms.TextInput(attrs={"class":"pull-right"} ))
    cost_from = forms.FloatField(label="from", required=False, widget = forms.TextInput(attrs={} ))
    cost_to = forms.FloatField(label="to", required=False, widget = forms.TextInput(attrs={} ))
    currency = forms.ChoiceField(widget=forms.Select(attrs={"class":"select76px"}), choices=CURRENCY_CHOICES)

boats/gallery/forms.py
# -*- coding: utf-8 -*-
from django.utils.safestring import mark_safe
from django import forms
from models import Item

class AdminImageWidget(forms.FileInput):
    """
    A ImageField Widget for admin that shows a thumbnail.
    """
    def __init__(self, attrs={}):
        super(AdminImageWidget, self).__init__(attrs)
    def render(self, name, value, attrs=None):
        output = []
        if value and hasattr(value, "url"):
            output.append((u'<a target="_blank" href="%s"><img src="%s" style="height: 100px;" /></a>' % (value.url, value.url)))
        output.append(super(AdminImageWidget, self).render(name, value, attrs))
        return mark_safe(u''.join(output))

class ImagePreviewForm(forms.ModelForm):
    #image = forms.FileField(label=u"Photo",widget=AdminImageWidget)
    class Meta:
        model = Item
        widgets = {'img':AdminImageWidget}

boats/articles/views.py
# -*- coding: utf-8 -*-
from .. decorators import render_to, render_to_json
from django.views.decorators.csrf import csrf_exempt

from django.template import RequestContext
from django.http import Http404,HttpResponse, HttpRequest
from django.shortcuts import render_to_response, HttpResponseRedirect, redirect, get_object_or_404, render
from django.core.urlresolvers import reverse

from django.db.models import Q
from boats.articles.models import Article, Category
from boats.catalog.models import Product, Ad
from django.contrib.contenttypes.models import ContentType
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
import re


def articles_show(request,slug):
    if slug=='all':
        articles = Article.objects.order_by('-pub_date')
    else:
        articles = Article.objects.filter(category__slug=slug).order_by('-pub_date')

    categories = Category.objects.order_by('-priority')
    paginator = Paginator(articles, 12)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    context = {
        'articles': articles,
        'categories': categories,
    }
    
    if request.session.get('articles_display'):
        s = request.session['articles_display']
        if s == 'list':
            return render(request, 'articles/articles_list.html', context)
        elif s == 'tiles':
            return render(request, 'articles/articles_tiles.html', context)
            
    return render(request, 'articles/articles_tiles.html', context)

@render_to('articles/article_details.html')
def article_details(request,slug):
    article = get_object_or_404(Article, slug=slug)

    #находит похожие статьи по тегам разделённым запятой
    for tag in article.tags.replace(' ', '').split(','):
        try:
            query = query | Q(tags__icontains = tag)
        except NameError:
            query = Q(tags__icontains = tag)
    sub_articles = Article.objects.exclude(id = article.id).filter(query)[:4]
    #находит похожие статьи по категориям, если найденных по тегам меньше 4
    if sub_articles.count() < 4:
        sub_articles = Article.objects.exclude(id= article.id).filter(query | Q(category=article.category))[:4]

    categories = Category.objects.all()
    return {
        'categories': categories,
        'article': article,
        'sub_articles': sub_articles,
    }


def articles_display(request,slug):
    if request.session.get('articles_display'):
        s = request.session['articles_display']
        if slug=="list":
            s = "list"
        else:
            s = "tiles"
    else:
        s = "list"

    request.session['articles_display'] = s
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@render_to('search.html')
@csrf_exempt
def search(request):
    er = ''
    results = {}
    count = 0
    search_words = ""
    types = ContentType.objects.get_for_models(Article, Ad, Product,)
    if 'search_words' in request.POST and len(request.POST.get('search_words')):
        search_words = re.sub(" +"," ",request.POST['search_words']).strip(" ")
        for tag in search_words.split(" "):
            try:
                query = query | Q(title__icontains = tag) | Q(text__icontains=search_words)
            except NameError:
                query = Q(tags__icontains = tag) | Q(title__icontains = tag) | Q(text__icontains=search_words)
        results = Article.objects.filter(query)
        count = results.count()
        if not len(results):
            er = u'По вашему запросу не найдено ни одной записи.'
        results = Paginator(results, 20)
        page = request.GET.get('page')
        try:
            results = results.page(page)
        except PageNotAnInteger:
            results = results.page(1)
        except EmptyPage:
            results = results.page(paginator.num_pages)
    return {
        'search_words': search_words,
        'count': count,
        'er': er,
        'results': results,
    }

boats/gallery/views.py
# -*- coding: utf-8 -*-
from .. decorators import render_to, render_to_json
from models import Gallery, Item
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
from django.shortcuts import render_to_response, get_object_or_404

@render_to("gallery/gallery_list.html")
def gallery_list(request):
    galleries = Gallery.objects.all().order_by('-pub_date')
    galleries = Paginator(galleries, 6)
    page = request.GET.get('page', 1)
    try:
        cur_list = galleries.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        cur_list = galleries.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        cur_list = galleries.page(paginator.num_pages)
    return {
        'galleries': cur_list
    }

@render_to("gallery/one_gallery.html")
def one_gallery(request, slug):
    gallery = get_object_or_404(Gallery, slug=slug)
    return {
        'gallery': gallery
    }

def load_more(request):
    try:
        page = int(request.GET['page'])
    except :
        raise Http404
    galleries = Gallery.objects.all().order_by('-pub_date')
    galleries = Paginator(galleries, 6)
    try:
        cur_list = galleries.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        cur_list = galleries.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        cur_list = galleries.page(paginator.num_pages)
    return render_to_response("gallery/includes/more.html",{
        'galleries':cur_list,
         }
    )

boats/templates/catalog/inclusion/catalog_ad_filter_list.html
{% if filters.items %}
<div class="span12 silverBackgraund">
	<p>ВАШ ВЫБОР</p>
</div>
<div style="margin: 0px" class="span12 border">
	{% for id, name in filters.items %}
    <ul>
    	<li><a href="/catalog/ads/del/filter/{{ id }}/"><i class="icon-remove-sign opa"></a></i>{{ name }}</li>
    </ul>
    {% endfor %}
</div>
{% endif %}

boats/templates/catalog/inclusion/catalog_search_form.html
<div class="span12 details" style="margin: 10px 0px 0px 0px">
    <div class="row-fluid">
        <div class="span12 silverBackgraund">
            <p style="padding-left: 45px;">ДЕТАЛИ</p>
        </div>
        <div class="span12 border" style="margin: 0px">
            <p class="vse">Всё о модели: </p>
            {{ CatalogModelSearchForm.model_brand }}
            <div id="id_div_model_product">{{ CatalogModelSearchForm.model_product }}</div>

            <button class="blueButton" id="id_model_search_button">СМОТРЕТЬ</button>
        </div>
    </div>

        <div class="row-fluid">
            <div class="span12 search18" style="margin: 10px 0px 0px 0px">
                <div class="row-fluid">
                    <div class="span12 silverBackgraund">
                        <p class="search" style="padding-left: 45px">ПОИСК</p>
                    </div>
                    <form action="/catalog/boats/search/" method="POST">{% csrf_token %}
                        <div class="span12 border" style="margin: 0px; padding-left: 7px;">
                            {% for error in CatalogBoatSearchFormErrors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                            <p class="podbor">Подобрать яхту: </p>
                            {{ CatalogBoatSearchForm.boat_brand }}
                            <div class="row-fluid">
                                <div class="span12">
                                    <p>Длина: </p>
                                    <p class="pull-left">oт</p>
                                    {{ CatalogBoatSearchForm.boat_length_from }}
                                    <p class="pull-left">до</p>
                                    {{ CatalogBoatSearchForm.boat_length_to }}
                                </div>
                            </div>
                            <select size="1" id="id_length_type" class="meters">
                                <option value="Метров">Метров</option>
                                <option value="Футов">Футов</option>
                            </select>
                            <div class="row-fluid">
                                <div class="span12">
                                    <p>Тип яхты:</p>
                                    <p class="radio18">
                                        {% for item in CatalogBoatSearchForm.boat_kind %}
                                        {{ item }}
                                        {% endfor %}
                                    </p>
                                </div>
                            </div>


                            <input class="blueButton" type="submit" name="boat-search" value="ПОДОБРАТЬ">
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>

<script type="text/javascript">
function model_search_select_linked(){
  $.get('/catalog/search/model/ajax/?brand='+$('#id_model_brand').val(), function(data) {
        $("#id_div_model_product").html(data);
    });
};

$(function() {
  $('#id_model_brand').on('change', function() {
    model_search_select_linked();
  });

  $.get('/catalog/search/model/ajax/?brand='+$('#id_model_brand').val(), function(data) {
        $("#id_div_model_product").html(data);
  });

  //перенаправляем по клику при выборе марки и модели на сформированый урл
  $('#id_model_search_button').click(function(){
    if($("#id_model_product").val()!="") {
        window.location = "/catalog/product/details/"+$("#id_model_product").val();
    }
    else {
        alert("Выберите модель");
    }
  });

  function IsNumeric(input){
    var RE = /^-{0,1}\d*\.{0,1}\d+$/;
    return (RE.test(input));
  }

  //конвертирует футы в метры и наоборот
  $('#id_length_type').on('change', function() {
    var length_from = $('#id_boat_length_from');
    var length_to = $('#id_boat_length_to');
    if($(this).val()=='Футов') {
        if(!$(length_from).val()==''){
            if(IsNumeric($(length_from).val())){
                $(length_from).val(($(length_from).val()*3.2).toFixed(2));
            };
        };
        if(!$(length_to).val()==''){
            if(IsNumeric($(length_to).val())){
                $(length_to).val(($(length_to).val()*3.2).toFixed(2));
            };
        };
    };
    if($(this).val()=='Метров') {
        if(!$(length_from).val()==''){
            if(IsNumeric($(length_from).val())){
                $(length_from).val(($(length_from).val()/3.2).toFixed(2));
            };
        };
        if(!$(length_to).val()==''){
            if(IsNumeric($(length_to).val())){
                $(length_to).val(($(length_to).val()/3.2).toFixed(2));
            };
        };
    };

  });


});
</script>

boats/templates/catalog/inclusion/footer_watertransport_list.html
<div class="span3 colorSilver">
    <ul>
        <li><a href="/catalog/category/all/" style="color: #59473e">КАТАЛОГ</a></li>
        {% for item in watertransport %}
        <li><a href="/catalog/brand/list/{{ item.slug }}/">{{ item.name }}</a></li>
        {% endfor %}
        <li><a href="#">&nbsp;</a></li>
        <li><a href="#">&nbsp;</a></li>
        <li>Сделано в <a href="#" style="text-decoration: underline;color: #59473e;">New Line</a></li>
    </ul>
</div>

boats/templates/catalog/inclusion/mini_brands_list.html
<div id="smallLogo" >
    <div class="span1">
        <ul>
            {% for item in brands %}
                <li>
                    <a href="/catalog/brand/details/{{ item.slug }}">
                        <img src="{{ item.logo.url }}" rel="tooltip" title="{{ item.name }}">
                    </a>
                </li>
            {% endfor %}
            <li><a href="/catalog/brand/all/"><p>ВСЕ МАРКИ></p> </a></li>
        </ul>
    </div>
</div>

boats/templates/catalog/inclusion/model_form_ajax.html
<select name="model_product" id="id_model_product">
	{% if products %}
		<option value="">-------</option>
		{% for item in products %}
			<option value="{{ item.slug }}">{{ item.title }}</option>
		{% endfor %}
	{% else %}
		<option value="">-------</option>
	{% endif %}
</select>

boats/templates/catalog/inclusion/popular_transport_list.html
{% load staticfiles %}
{% if products %}
<div class="span12 silverBackgraund" style="margin: 20px 0px 0px 0px">
    <p style="padding-left: 400px">САМЫЕ ПОПУЛЯРНЫЕ МОДЕЛИ</p>
</div>

<div class="span12" style="margin-left: 0px">
    <div class="row-fluid">
        <div id="myCarousel" class="carousel slide">
            <!-- Carousel items -->
            <div class="carousel-inner">
                {% for item in products %}
                {% if forloop.counter0|divisibleby:"6" %}
                    {% if forloop.counter0 == 0 %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                {% endif %}
                    <a href="/catalog/product/details/{{ item.slug }}/">
                    <div>
                        <img src="{{ item.preview.url }}">
                        <p class="name">{{ item.brand }}</p>
                        <p class="name">{{ item.title }}</p>
                    </div>
                    </a>
                {% if forloop.counter|divisibleby:"6" or forloop.last %}
                    </div>
                {% endif %}
                {% endfor %}
            </div>
            <!-- Carousel nav -->
            <a class="carousel-control left width970px" href="#myCarousel" data-slide="prev" style=" margin-top: -10px; "><img src="{% static "img/buttonleft.png" %}"></a>
            <a class="carousel-control right1 width970px" href="#myCarousel" data-slide="next" style=" margin-top: -10px; "><img src="{% static "img/buttonright.png" %}"></a>
        </div>

    </div>
</div>
{% endif %}